version: '3.4'
services:
  postgres:  
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_monitor_dev
    # volumes:
      # - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
# volumes:
  # pgdata:
